---
title: "seagrass_clamshells_2017"
author: "Tiff Stephens"
date: "3/20/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(plyr)
library(tidyr)
```



```{r}
# upload required RAW dataframes
df.shells <- read.csv("/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/seagrass_clam_shells_2017_RAW.csv", stringsAsFactors = FALSE, header = TRUE)

df.coor <- read.csv("/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/sites_coordinates.csv", stringsAsFactors = FALSE, header = TRUE)
```

```{r}
# rename columns for clarity
colnames(df.shells)[which(names(df.shells) == "Site")] <- "site_code"
colnames(df.shells)[which(names(df.shells) == "Date")] <- "date_MMDDYYYY"
colnames(df.shells)[which(names(df.shells) == "YYYYMMDD")] <- "date_YYYYMMDD"
colnames(df.shells)[which(names(df.shells) == "Transect")] <- "transect_location"
colnames(df.shells)[which(names(df.shells) == "TransectBin")] <- "transect_bin_no"
colnames(df.shells)[which(names(df.shells) == "Transect_m")] <- "transect_bin_m"
colnames(df.shells)[which(names(df.shells) == "sp_code")] <- "species_code"
colnames(df.shells)[which(names(df.shells) == "Death")] <- "death_estimate"
colnames(df.shells)[which(names(df.shells) == "Notes")] <- "notes"
colnames(df.shells)[which(names(df.shells) == "Measurers")] <- "measurers"

colnames(df.coor)[which(names(df.coor) == "site")] <- "site_code"
colnames(df.coor)[which(names(df.coor) == "latitude")] <- "latitude_N"
colnames(df.coor)[which(names(df.coor) == "longitude")] <- "longitude_E"
```

```{r}
# joing add site names to DF
df.shelldeath <- left_join(df.shells, df.coor, by = c("site_code"))
```

```{r}
colnames(df.shelldeath)

# reorganize column order
df.shelldeath <- df.shelldeath[c("site_code","site_name","latitude_N","longitude_E","date_MMDDYYYY","date_YYYYMMDD","transect_location","transect_bin_no","transect_bin_m","species_common","species_scientific","species_code","death_estimate","width_mm","notes","measurers")]

```

```{r}
# print final, cleaned .csv file
write.csv(df.shelldeath, "/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/DATA_ARCHIVING/seagrass_clamshells_2017/seagrass_shelldeath_2017_CLEANDATA.csv", row.names = TRUE)

# print supporting DFs as .csv files to go with .Rmd file on KNB
write.csv(df.shells, "/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/DATA_ARCHIVING/seagrass_clamshells_2017/df.shells_RAW.csv", row.names = TRUE)
write.csv(df.coor, "/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/DATA_ARCHIVING/seagrass_clamshells_2017/df.coor_RAW.csv", row.names = TRUE)
```



