---
title: "Macronutrients"
author: "Nicole LaRoche"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading libraries and data
```{r, libraries and data, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)


plab <- read.csv("plab.csv")
summary <- read.csv("Summary_PC.csv")
```


I want to combine info from the summary file into the Moisure, bomb, and lipid files
```{r, new moisture file, message=FALSE}
summary.short <- select(summary, SIN, Size.mm, Species, Frozen.Weight,
                        Live.Weight, Dissected.Weight, Site.location, Season, PreyCat)
all <- left_join(plab, summary.short, by="SIN")
```


Converting from KJ/dry mass to KJ/wet mass
```{r, convert to wet mass, message=FALSE}
# remember moisture is currently in xx.xx, and we need 0.xxxx
all$KJ.wetgram <-NA
all$KJ.wetgram <- (1-(all$moisture/100))*all$KJ
#Removing NA in PreyCat
all<-all %>% drop_na(PreyCat)
```


## KJ/wet g vs length (by species)
```{r, graph KJ vs length, echo = FALSE, message=FALSE}
ggplot(data= all, aes(x=Size.mm, y=KJ)) +
  geom_point() + theme_few() +
  stat_smooth(method= "lm") +
  labs(x= "Length (in mm)", y="KJ/gram (by dry mass)")  +
  facet_wrap(vars(PreyCat), scales= "free")
```


## % Lipid vs length (by species) 

```{r, graph lipid vs length, echo= FALSE, message=FALSE}
ggplot(data= all, aes(x=Size.mm, y=lipid_wet)) +
  geom_point() + theme_few() +
  stat_smooth(method= "lm") +
  labs(x= "Length (in mm)", y="% Lipid (wet mass)")  +
  facet_wrap(vars(PreyCat), scales= "free")
```

```{r, graph protein vs length, echo= FALSE, message=FALSE}
ggplot(data= all, aes(x=Size.mm, y=protein_wet)) +
  geom_point() + theme_few() +
  stat_smooth(method= "lm") +
  labs(x= "Length (in mm)", y="% Protein (wet mass)")  +
  facet_wrap(vars(PreyCat), scales= "free")
```

## Now to put them together
```{r, KJ and Lipid vs length, echo = FALSE, Message = FALSE}
ggplot(data= all) + theme_few() +
  geom_point(aes(x=Size.mm, y=lipid_wet, color= "% Lipid")) + 
  stat_smooth(aes(x=Size.mm, y=lipid_wet, color= "% Lipid"), method= "lm") +
  labs(x= "Length (in mm)", y="% Lipid")  +
  geom_point(aes(x=Size.mm, y=KJ.wetgram, color="KJ/g")) +
  stat_smooth(aes(x=Size.mm, y=KJ.wetgram, color="KJ/g"), method= "lm") +
  scale_color_manual(name='', values=c("% Lipid"="Red", "KJ/g"="Blue"))+
  scale_y_continuous(sec.axis = sec_axis(~., name ="KJ/g (wet mass)" )) +
  facet_wrap(vars(PreyCat), nrow = 4, scales= "free")
```

### % Lipid vs % Protein (wet mass values)
```{r, lipid v protein, echo=FALSE}
ggplot(data= all, aes(x=protein_wet, y=lipid_wet, color = PreyCat)) +
  theme_few() +
  geom_point() +
  stat_smooth(formula = y~x, se= FALSE, method= lm)

```

```{r, season - lipid, echo=FALSE, warning=FALSE}
ggplot(data= all, aes(x=Season, y=lipid_wet)) +
  geom_point() + theme_few() +
  stat_smooth(aes(x=as.numeric(Season), y=lipid_wet)) +
  labs(x= "", y="% Lipid")  +
  facet_wrap(vars(PreyCat), scales = "free", nrow=4)
```

```{r, season - protein, echo=FALSE, warning=FALSE}
ggplot(data= all, aes(x=Season, y=protein_wet)) +
  geom_point() + theme_few() +
  stat_smooth(aes(x=as.numeric(Season), y=protein_wet)) +
  labs(x= "", y="% Lipid")  +
  facet_wrap(vars(PreyCat), scales = "free", nrow=4)
```

```{r, bomb species, warning= FALSE, echo=FALSE}
ggplot(data= all, aes(y=KJ, x=Season), na.rm=TRUE) +
  geom_point() + theme_few() +
  stat_smooth(aes(x=as.numeric(Season), y=KJ)) +
  labs(x="Season", y="KJ (g)") +
  facet_wrap(vars(PreyCat))
```

