---
title: "Untitled"
author: "Tiff Stephens"
date: "1/6/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
# Load your libraries
library(dplyr); library(tidyr); library(ggplot2)
theme_set(theme_classic())
```

This Rmd file is for cleaning the RAW discrete sediment data for each seagrass site.

First, import the RAW data:
```{r}
df.sedpit <- read.csv("https://raw.githubusercontent.com/APECS-ak/APECS-master-repos/master/ALL_DATA/seagrass_seaotter_pit_sediment_2017_RAW.csv", stringsAsFactors = FALSE, header = TRUE)
```

```{r}
#Now, understand the structure of the data, look at the data, visualize the data.

# check out the overall structure of the dataframe
str(df.sedpit)

# first, look at the numeric and factor classifications of variables. Many factors are ordinal; there classifications need to reflect this. 
#df.sedpit$trans_bin <- as.ordered(df.sedpit$trans_bin)
#df.sedpit$trans_m <- as.ordered(df.sedpit$trans_m)
#df.sedpit$sed1_no <- as.ordered(df.sedpit$sed1_no)
#df.sedpit$sed2_no <- as.ordered(df.sedpit$sed2_no)
#df.sedpit$sedno_avg <- as.ordered(df.sedpit$sedno_avg)

# the last column of the df is useless/empty, exclude it from the working df. Check that it was removed successfully (it was)
df.sedpit <- within(df.sedpit, rm(X))
df.sedpit <- within(df.sedpit, rm(sedno_avg)) # delete this to calculate means using R, not excel
str(df.sedpit)

# no look at the tail-end of the observations...
tail(df.sedpit, n = 15) # change the number of rows by modifying n value

# ...this reveals that the last 10 rows are empty; exclude those and re-check df. 
df.sedpit <- df.sedpit[-c(631:640),]
tail(df.sedpit, n = 15)
str(df.sedpit)

# OK! All obvious useless variables + observations are removed from the edges of the df.
# irregularities within the df can be explored using histograms of numeric data
hist(df.sedpit$pit_bin)
hist(df.sedpit$sed1_no)
hist(df.sedpit$sed2_no)
hist(df.sedpit$sedno_avg)


summary(df.sedpit)

```

```{r}
# checking for missing values
head(df.sedpit)

mean(df.sedpit$pit_bin)
mean(df.sedpit$pit_bin, na.rm = TRUE)

mean(df.sedpit$sedno_avg)
mean(df.sedpit$sedno_avg, na.rm = TRUE)

```







```{r}
write.csv(df.sedpit,'seagrass_seaotter_pit_sediment_2017_CLEAN.csv')
```



