---
title: "Site_selection_map_2018"
author: "Wendel Raymond"
date: "March 13, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Site Selection
Maps and data for 2018 field season.

```{r libraries, echo = FALSE, warning=FALSE, message=FALSE}
library(sp)
library(rgdal)
library(rgeos)
library(maptools)
library(leaflet)
library(dplyr)
library(raster)
library(ggplot2)
library(DT)

theme_set(theme_classic())
```

```{r data, echo=FALSE,warning=FALSE, message=FALSE}
## Transect ##
tran.dat <- read.csv("../ALL_DATA/eelgrass_and_grazer_2017_derived.csv", header = TRUE, stringsAsFactors = FALSE)

## Sea Otter Impact Index ##
so.index <- read.csv("../ALL_DATA/sea_otter_impact_index_2017_new.csv", stringsAsFactors = FALSE, header = TRUE)

## Sediment ##
sed.site <- read.csv("../ALL_DATA/seagrass_seaotter_pit_sediment_2017_RAW.csv", stringsAsFactors = FALSE, header = TRUE)

## Crab ##
crab.dat <- read.csv("../All_DATA/eelgrass_crab_pot_derived.csv", header = TRUE, stringsAsFactors = FALSE)
crab.dat$string <- as.character(crab.dat$string)

## Fish ##
fish.dat <- read.csv("../ALL_DATA/eelgrass_beach_seine_derived.csv", header = TRUE, stringsAsFactors = FALSE)

## Fish Taxonomy ##
fish.tax <- read.csv("../ALL_DATA/fish_taxonomy_RAW.csv", header = TRUE, stringsAsFactors = FALSE)

## Sediments transform ##
seds <- sed.site %>% 
  filter(trans_type == "Inside") %>% 
  group_by(site) %>% 
  summarise(sed_inside_prim = mean(sed1_no, na.rm = TRUE))

dat <- merge(tran.dat, seds, by = "site")

## Light availability calculation ##

dat$light_avail <- (dat$light_intensity_umol.m2.sec_transect / dat$light_intensity_umol.m2.sec_surface)

## Crab data preparation ##
crab.site <- crab.dat %>% 
  group_by(site) %>% 
  summarise(crab_count = mean(count, na.rm = TRUE),
            crab_mass = mean(mass_g, na.rm = TRUE))

dat <- merge(dat, crab.site, by = "site")

crab.site.fuk <- crab.dat %>% 
  filter()

## Crab data preparation ##
crab.rock <- crab.dat %>% 
  filter(sp_code == "CRABDUN" | sp_code == "CRABRR" | sp_code == "CRAGRA"| sp_code == "UNRKCB") %>% 
  group_by(site) %>% 
    summarise(rock_count = mean(count, na.rm = TRUE),
            rock_mass = mean(mass_g, na.rm = TRUE))

dat <- merge(dat, crab.rock, by = "site")

## Fish data preparation append taxonomy ##
fish.dat <- merge(fish.dat, fish.tax, by.x = "species_scientific", by.y = "scientific_name", all = TRUE)

## Shoreline Data ##
shore <- readOGR(dsn = "../ALL_DATA/spatial_data", layer="POW Shoreline")
shore <- spTransform(shore, CRS("+proj=longlat +datum=WGS84"))

# Eelgrass #
eelgrass_c <- as.SpatialLines.SLDF(subset(shore, ZOS == "C"))
eelgrass_p <- as.SpatialLines.SLDF(subset(shore, ZOS == "P"))
```

## Study Area
```{r icon, echo = FALSE}
# Eelgrass Icon
egIcon <- makeIcon(
  iconUrl = "http://moziru.com/images/sea-grass-clipart-1.png",
  iconWidth = 25, iconHeight = 15,
  iconAnchorX = 12.5, iconAnchorY = 0
)
```

```{r map, echo = FALSE}
leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addMarkers(data = dat, ~longitude, icon = egIcon, ~latitude, popup = ~site) %>% 
  addPolylines(data = eelgrass_p, color = "lightgreen", fill = NA, opacity = 1, group = "Patchy eelgrass") %>% 
  addPolylines(data = eelgrass_c, color ="darkgreen", fill = NA, opacity = 1, group = "Continuous eelgrass") %>% 
  addLayersControl(overlayGroups = c("Patchy eelgrass", "Continuous eelgrass"), options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend("bottomleft", colors = c("lightgreen", "darkgreen"), labels = c("Patchy eelgrass", "Continuous eelgrass"), title = "Legend", opacity = 1)
```

## 2017 Data 
### Sea Otter Index
```{r soi, echo = FALSE}
soi <- dat[, c(1,2, 45:51)]
soi <- cbind.data.frame(soi[,c(1,2,5,7)], round(soi[, c(3,4,6,8,9)],2))

ggplot(soi, aes(reorder(site, sea_otter_index), sea_otter_index, col = sea_otter_index)) +
  geom_point(size = 4)+
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "Site", y = "Sea otter impact Index", col = "Sea otter impact Index") +
  theme(text = element_text(size = 12), axis.ticks = element_line(size = 2)) +
  theme(axis.text.x = element_text(angle = 90))

datatable(soi, options = list(pageLength = 21))
```

### Environmental Data
```{r envi, echo = FALSE}
envi <- dat[, c(1,2, 15:44, 52:61, 115, 116)]
envi <- cbind.data.frame(envi[, c(1,2)], round(envi[, 3:44], 2))

datatable(envi, options = list(pageLength = 21))
```

### Biological Data
```{r bio, echo = FALSE}
bio <- dat[, c(1,2, 65:114, 117:120)]

datatable(bio, options = list(pageLength = 21))
```

