---
title: "elevations_2018"
author: "Tiff Stephens"
date: "10/1/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr); library(tidyr); library(plyr); library(reshape2); library(lubridate); library(ggplot2); library(DT); library(leaflet); library(htmlwidgets); library(htmltools); library(shiny); library(mapview); library(sp); library(sf); library(knitr); library(cowplot); library(ggpmisc); library(DT); library(plyr); library(magick)
```

```{r}
# import RAW data
df.elev <- read.csv("/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_DATA/TIFF_seagrass/2018_data/elevation_density.csv", stringsAsFactors = FALSE, header = TRUE)
```

```{r}
# look at structure of df. elev
glimpse(df.elev)
```

```{r}
# convert/calculate (1) MLLW feet to MLLW centimeters, (2) MLLW cm values for Fucus elevations, (3) MLLW cm values for seagrass elevations
df.elev = df.elev %>% 
  mutate(waterline_elev_mllw_cm = waterline_elev_mllw_ft * 30.48, na.rm = TRUE) %>%
  mutate(fucus_upper_elev_mllw_cm = waterline_elev_mllw_cm + (waterline_elev_stadia_avg_cm - fucus_upper_elev_stadia_cm), na.rm = TRUE) %>%
  mutate(fucus_lower_elev_mllw_cm = waterline_elev_mllw_cm + (waterline_elev_stadia_avg_cm - fucus_lower_elev_stadia_cm), na.rm = TRUE) %>%
  mutate(fucus_mean_elev_mllw_cm = (fucus_upper_elev_mllw_cm + fucus_lower_elev_mllw_cm) / 2, na.rm = TRUE) %>%
  mutate(fucus_band_height_cm = fucus_upper_elev_mllw_cm - fucus_lower_elev_mllw_cm, na.rm = TRUE) %>%
  mutate(edge_diffuse_elev_mllw_cm = waterline_elev_mllw_cm + (waterline_elev_stadia_avg_cm - edge_diffuse_elev_stadia_cm), na.rm = TRUE) %>%
  mutate(edge_continuous_elev_mllw_cm = waterline_elev_mllw_cm + (waterline_elev_stadia_avg_cm - edge_continuous_elev_stadia_cm), na.rm = TRUE) %>%
  mutate(diffuse_band_height_cm = edge_diffuse_elev_mllw_cm -edge_continuous_elev_mllw_cm, na.rm = TRUE)


# calculate beach slope and diffuse band area
df.elev = df.elev %>%
  mutate(beach_slope = diffuse_band_height_cm / (sqrt(((distance_diffuse_band_cm)^2)-((diffuse_band_height_cm)^2))), na.rm = TRUE) %>%
  mutate(area_diffuse_band_m2 = ((distance_diffuse_band_cm)/100) * 50, na.rm = TRUE)
```

```{r}
# convert all density data to meters squared
df.elev = df.elev %>% 
  mutate(shoot_density_inside_m2 = shoot_density_inside_0.25m2 * 4, na.rm = TRUE) %>%
  mutate(shoot_density_continuous_m2 = shoot_density_continuous_0.25m2 * 4, na.rm = TRUE) %>%
  mutate(shoot_density_diffuse_m2 = shoot_density_diffuse_0.25m2 * 4, na.rm = TRUE) %>%
  mutate(flower_density_inside_m2 = flower_density_inside_0.25m2 * 4, na.rm = TRUE) %>%
  mutate(flower_density_continuous_m2 = flower_density_continuous_0.25m2 * 4, na.rm = TRUE) %>%
  mutate(flower_density_diffuse_m2 = flower_density_diffuse_0.25m2 * 4, na.rm = TRUE)


colnames(df.elev)

df.elev <- df.elev[, -c(9:15,17:24)] # remove these columns
names(df.elev)[names(df.elev) == 'distance_diffuse_band_cm'] <- 'diffuse_band_width_cm' # rename site columns

glimpse(df.elev)
df.elev <- df.elev[c("site_name","site_code","latitude_N","longitude_E","so_region","date_dd.mm.yy","cage_present","replicate","beach_slope","fucus_upper_elev_mllw_cm","fucus_lower_elev_mllw_cm","fucus_mean_elev_mllw_cm","fucus_band_height_cm","edge_diffuse_elev_mllw_cm","edge_continuous_elev_mllw_cm","diffuse_band_width_cm","diffuse_band_height_cm","area_diffuse_band_m2","shoot_density_diffuse_m2","shoot_density_continuous_m2","shoot_density_inside_m2","flower_density_diffuse_m2","flower_density_continuous_m2","flower_density_inside_m2")]
```


\DataExport
```{r export}
# Data Export
write.csv(df.elev, "/Users/tiff/Desktop/R Studio/APECS-master-repos/ALL_Data/TIFF_seagrass/2018_data/elevation_density_2018_CLEAN.csv", row.names = FALSE)
```

